'use strict';
const http=require('http'),fs=require('fs'),path=require('path');const {URL}=require('url');
function reqCompat(structured,flat){try{return require(structured)}catch(e){if(e&&e.code==='MODULE_NOT_FOUND'){return require(flat)}throw e}}
const MODULES=reqCompat('./config/modules','./modules'),CONNECTORS=reqCompat('./config/connectors','./connectors'),ENGINES=reqCompat('./config/engines','./engines');
const {ModuleStore}=reqCompat('./lib/module-store','./module-store'),{LongMemory}=reqCompat('./lib/memory','./memory'),{AIEngine}=reqCompat('./lib/ai','./ai'),{IntegrationBus}=reqCompat('./lib/integration-bus','./integration-bus'),{route}=reqCompat('./lib/router','./router'),{EventBus}=reqCompat('./lib/event-bus','./event-bus'),{EngineRuntime}=reqCompat('./lib/engine-runtime','./engine-runtime'),{WorkerManager}=reqCompat('./lib/worker-manager','./worker-manager'),{tenantContext}=reqCompat('./lib/tenant','./tenant');
const envFile=path.join(__dirname,'.env');if(fs.existsSync(envFile)){for(const line of fs.readFileSync(envFile,'utf8').split(/\r?\n/)){const t=line.trim();if(!t||t.startsWith('#')||!t.includes('='))continue;const i=t.indexOf('='),k=t.slice(0,i).trim();let v=t.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(!(k in process.env))process.env[k]=v;}}
const PORT=Number(process.env.PORT||8787),ROOT=__dirname,DATA=path.join(ROOT,'data'),MEMORY=path.join(ROOT,'memory');fs.mkdirSync(DATA,{recursive:true});fs.mkdirSync(MEMORY,{recursive:true});
const moduleStore=new ModuleStore(DATA,MODULES),memory=new LongMemory(MEMORY),eventBus=new EventBus({moduleStore,memory}),ai=new AIEngine({modules:MODULES,memory,moduleStore,engines:ENGINES}),bus=new IntegrationBus({moduleStore,memory,connectors:CONNECTORS,eventBus}),engineRuntime=new EngineRuntime({modules:MODULES,engines:ENGINES,moduleStore,memory,ai,eventBus}),workers=new WorkerManager({engines:ENGINES,moduleStore,eventBus});
const DEFAULT_CTX={tenant_id:'default',dealer_id:'default'};Object.keys(MODULES).forEach(id=>{moduleStore.load(id,DEFAULT_CTX);memory.load(id,DEFAULT_CTX)});memory.load('core',DEFAULT_CTX);
function json(res,status,obj){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj));}
function readBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>10_000_000){reject(new Error('Payload te groot'));req.destroy();}});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch{reject(new Error('Ongeldige JSON'))}});req.on('error',reject);});}
function safeModule(id){return Object.prototype.hasOwnProperty.call(MODULES,id)}
function requestContext(req,body={}){return tenantContext({tenant_id:body.tenant_id||req.headers['x-foundly-tenant']||'default',dealer_id:body.dealer_id||req.headers['x-foundly-dealer']||'default'});}
function systemStatus(ctx){return {version:'2.9.1',tenant:ctx,ai:ai.providerStatus(),connectors:bus.connectorStatus(),engines:Object.keys(ENGINES).map(id=>engineRuntime.status(id,ctx)),workers:workers.definitions(),memory:{core:memory.stats('core',ctx),modules:Object.keys(MODULES).map(id=>memory.stats(id,ctx))}};}
async function coreAsk(message,sharedContext={}){const ctx=tenantContext(sharedContext),choices=route(message,{max:4}),agentResults=[];for(const c of choices){const result=await engineRuntime.ask(c.id,message,{...sharedContext,...ctx,router_score:c.score});agentResults.push({module:c.id,name:MODULES[c.id].naam,...result});if(c.score>0&&choices[0].score>=2&&c.score<choices[0].score-1)break;}if(agentResults.length===1)return {answer:agentResults[0].answer,modules:agentResults,mode:'single_engine',tenant:ctx};const synthesisPrompt=`Gebruikersvraag: ${message}\n\nSpecialistische engine-antwoorden:\n${agentResults.map(x=>`[${x.name}] ${x.answer}`).join('\n\n')}\n\nMaak hiervan één samenhangend Nederlands Foundly-antwoord. Verzin geen data en benoem welke engine welke conclusie leverde als dat relevant is.`;let synthesis=null;try{synthesis=await ai.callProvider('data',synthesisPrompt,{tenant:ctx,agents:agentResults,memory:memory.recall('core',message,12,ctx)});}catch{}if(!synthesis)synthesis=agentResults.map(x=>`${x.name}: ${x.answer}`).join('\n\n');memory.remember('core',{type:'orchestration',text:`Vraag: ${message}\nAntwoord: ${synthesis}`,summary:message,importance:.72,tags:['core','multi_engine'],metadata:ctx},ctx);await eventBus.publish('core.orchestration.completed',{message,modules:agentResults.map(x=>x.module)},{...ctx,module_id:'automatisering'});return {answer:synthesis,modules:agentResults,mode:'multi_engine',tenant:ctx};}
async function handleApi(req,res,url){
  if(url.pathname==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,version:'2.9.1',architecture:'autonomous-independent-engines-shared-data-fabric-long-memory-multitenant',modules:Object.keys(MODULES).length,engines:Object.keys(ENGINES).length,ai:ai.providerStatus(),configured_connectors:bus.connectorStatus().filter(x=>x.configured).length,total_connectors:Object.keys(CONNECTORS).length});
  if(url.pathname==='/api/engines'&&req.method==='GET')return json(res,200,{engines:Object.keys(ENGINES).map(id=>engineRuntime.manifest(id))});
  if(url.pathname==='/api/connectors'&&req.method==='GET')return json(res,200,{connectors:bus.connectorStatus()});
  if(url.pathname==='/api/system/status'&&req.method==='GET'){const ctx=requestContext(req);return json(res,200,systemStatus(ctx));}
  if(url.pathname==='/api/core/ask'&&req.method==='POST'){const b=await readBody(req);if(!b.message)return json(res,400,{error:'message ontbreekt'});const ctx=requestContext(req,b.context||b);return json(res,200,await coreAsk(String(b.message),{...(b.context||{}),...ctx}));}
  if(url.pathname==='/api/data/ingest'&&req.method==='POST'){const b=await readBody(req);if(!b.source)return json(res,400,{error:'source ontbreekt'});const ctx=requestContext(req,b);return json(res,202,await bus.ingest({...b,...ctx}));}
  if(url.pathname==='/api/workers'&&req.method==='GET')return json(res,200,{workers:workers.definitions()});
  if(url.pathname==='/api/workers/tick'&&req.method==='POST'){const b=await readBody(req),ctx=requestContext(req,b);return json(res,200,{runs:await workers.tick(ctx),tenant:ctx});}
  const webhook=url.pathname.match(/^\/api\/webhook\/([^/]+)$/);if(webhook&&req.method==='POST'){const source=webhook[1];if(!CONNECTORS[source])return json(res,404,{error:'Onbekende connector'});const b=await readBody(req),ctx=requestContext(req,b),secret=process.env.FOUNDLY_WEBHOOK_SECRET;if(secret&&req.headers['x-foundly-secret']!==secret)return json(res,401,{error:'Ongeldige webhook secret'});return json(res,202,await bus.ingest({source,type:b.type||'webhook',items:Array.isArray(b.items)?b.items:[b],...ctx,metadata:{headers_safe:{'user-agent':req.headers['user-agent']||null}}}));}
  const engineAction=url.pathname.match(/^\/api\/engine\/([^/]+)\/(ask|execute|status)$/);if(engineAction){const id=engineAction[1],op=engineAction[2];if(!safeModule(id))return json(res,404,{error:'Onbekende engine'});if(op==='status'&&req.method==='GET')return json(res,200,engineRuntime.status(id,requestContext(req)));const b=await readBody(req),ctx=requestContext(req,b.context||b);if(op==='ask'&&req.method==='POST'){if(!b.message)return json(res,400,{error:'message ontbreekt'});return json(res,200,await engineRuntime.ask(id,String(b.message),{...(b.context||{}),...ctx}));}if(op==='execute'&&req.method==='POST'){if(!b.action)return json(res,400,{error:'action ontbreekt'});return json(res,202,await engineRuntime.execute(id,String(b.action),b.payload||{},ctx));}}
  const memSearch=url.pathname.match(/^\/api\/memory\/([^/]+)\/search$/);if(memSearch&&req.method==='GET'){const scope=memSearch[1],ctx=requestContext(req);if(scope!=='core'&&!safeModule(scope))return json(res,404,{error:'Onbekend geheugenscope'});return json(res,200,{items:memory.recall(scope,url.searchParams.get('q')||'',Number(url.searchParams.get('limit')||15),ctx),stats:memory.stats(scope,ctx)});}
  const memRoot=url.pathname.match(/^\/api\/memory\/([^/]+)$/);if(memRoot){const scope=memRoot[1];if(scope!=='core'&&!safeModule(scope))return json(res,404,{error:'Onbekend geheugenscope'});if(req.method==='GET'){const ctx=requestContext(req);return json(res,200,memory.load(scope,ctx));}if(req.method==='POST'){const b=await readBody(req),ctx=requestContext(req,b.metadata||b),rec=memory.remember(scope,{type:b.type||'manual',text:b.text||b.content,summary:b.summary,importance:b.importance??.8,tags:b.tags||[],metadata:{...(b.metadata||{}),...ctx},source:b.source||'manual'},ctx);if(!rec)return json(res,400,{error:'text ontbreekt'});return json(res,201,{memory:rec,stats:memory.stats(scope,ctx)});}}
  const m=url.pathname.match(/^\/api\/module\/([^/]+)(?:\/(ask|data|summary|memory))?$/);if(m){const moduleId=m[1],op=m[2];if(!safeModule(moduleId))return json(res,404,{error:'Onbekend onderdeel'});if(req.method==='GET'){const ctx=requestContext(req);if(!op)return json(res,200,{id:moduleId,module:MODULES[moduleId],engine:ENGINES[moduleId],database:moduleStore.summary(moduleId,ctx),memory:memory.stats(moduleId,ctx)});if(op==='summary')return json(res,200,{module:moduleStore.summary(moduleId,ctx),memory:memory.stats(moduleId,ctx),engine:ENGINES[moduleId]});if(op==='data')return json(res,200,moduleStore.load(moduleId,ctx));if(op==='memory')return json(res,200,{items:memory.recall(moduleId,url.searchParams.get('q')||'',Number(url.searchParams.get('limit')||15),ctx),stats:memory.stats(moduleId,ctx)});}if(req.method==='POST'){const b=await readBody(req),ctx=requestContext(req,b.context||b);if(op==='ask'){if(!b.message)return json(res,400,{error:'message ontbreekt'});return json(res,200,await engineRuntime.ask(moduleId,String(b.message),{...(b.context||{}),...ctx}));}if(op==='data'){const collection=b.collection||'records',allowed=['events','records','insights','tasks','connections','entities','preferences','decisions'];if(!allowed.includes(collection))return json(res,400,{error:'Onbekende collectie'});return json(res,201,moduleStore.add(moduleId,collection,b.record||{},{},ctx));}}}
  return false;
}
function serve(req,res,url){let p=url.pathname==='/'?'/index.html':url.pathname;p=path.normalize(p).replace(/^\.\.(\/|\\)/,'');const f=path.join(ROOT,p);if(!f.startsWith(ROOT)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found');}const ext=path.extname(f),types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.css':'text/css; charset=utf-8','.md':'text/plain; charset=utf-8'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res);}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(url.pathname.startsWith('/api/')){const handled=await handleApi(req,res,url);if(handled!==false)return;}serve(req,res,url);}catch(e){console.error(e);json(res,500,{error:e.message});}});server.listen(PORT,()=>console.log(`Foundly OS v2.9.1 draait op http://localhost:${PORT}`));
setInterval(()=>{workers.tick(DEFAULT_CTX).catch(()=>{});},15_000).unref();
